{
  "formatVersion": "1.1",
  "component": {
    "group": "org.xxxsarutahikoxxx.kotlin",
    "module": "HIDDevice",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "HIDDevice-2.0.3.jar",
          "url": "HIDDevice-2.0.3.jar",
          "size": 1056471,
          "sha512": "d649c3d9e1ee4ccee7b98e16536e2e89061737445241c403cf1e11905a2bbc801295d4909a5ede4c02e46358942a1b936ce08ea47221dc71fbc35151bc71d887",
          "sha256": "fdffe0b20c16e9840429aacfb82ceeee8bf5ff46fb9c55ea30b7b359bec5780d",
          "sha1": "58b91d795beacde673e458f4daa0a6e576fcd924",
          "md5": "93b4d8eaf8b4c844c0d77eae132dabf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "io.ultreia",
          "module": "bluecove",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.xxxsarutahikoxxx.kotlin",
          "module": "KotlinLibrary",
          "version": {
            "requires": "2.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "HIDDevice-2.0.3.jar",
          "url": "HIDDevice-2.0.3.jar",
          "size": 1056471,
          "sha512": "d649c3d9e1ee4ccee7b98e16536e2e89061737445241c403cf1e11905a2bbc801295d4909a5ede4c02e46358942a1b936ce08ea47221dc71fbc35151bc71d887",
          "sha256": "fdffe0b20c16e9840429aacfb82ceeee8bf5ff46fb9c55ea30b7b359bec5780d",
          "sha1": "58b91d795beacde673e458f4daa0a6e576fcd924",
          "md5": "93b4d8eaf8b4c844c0d77eae132dabf2"
        }
      ]
    }
  ]
}
