{
  "formatVersion": "1.1",
  "component": {
    "group": "org.xxxsarutahikoxxx.kotlin",
    "module": "HIDDevice",
    "version": "2.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "HIDDevice-2.0.6.jar",
          "url": "HIDDevice-2.0.6.jar",
          "size": 1056653,
          "sha512": "2b5d59a3a526f301e9e1c005cfcf7fd0ae6a2aa44f563fd88bee27fc15394edec19590c2aa0727dbe5e9c60c8d2521e74d57e67fc1a33e96414e408bb08f83f4",
          "sha256": "5801d608d57131971afca7714db9d155c6248e8b6ad1decf810b52b30b3ddac4",
          "sha1": "287758013f1b7063fe27929a00b3eb96dfd359f1",
          "md5": "6f4006559e6b3e287eaa2075e25f3ee0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "io.ultreia",
          "module": "bluecove",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.xxxsarutahikoxxx.kotlin",
          "module": "KotlinLibrary",
          "version": {
            "requires": "2.0.10"
          }
        }
      ],
      "files": [
        {
          "name": "HIDDevice-2.0.6.jar",
          "url": "HIDDevice-2.0.6.jar",
          "size": 1056653,
          "sha512": "2b5d59a3a526f301e9e1c005cfcf7fd0ae6a2aa44f563fd88bee27fc15394edec19590c2aa0727dbe5e9c60c8d2521e74d57e67fc1a33e96414e408bb08f83f4",
          "sha256": "5801d608d57131971afca7714db9d155c6248e8b6ad1decf810b52b30b3ddac4",
          "sha1": "287758013f1b7063fe27929a00b3eb96dfd359f1",
          "md5": "6f4006559e6b3e287eaa2075e25f3ee0"
        }
      ]
    }
  ]
}
