{
  "formatVersion": "1.1",
  "component": {
    "group": "org.xxxsarutahikoxxx.kotlin",
    "module": "HIDDevice",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "HIDDevice-2.0.2.jar",
          "url": "HIDDevice-2.0.2.jar",
          "size": 1056313,
          "sha512": "49219c3de2db6739aa73e6ebfaabd39fc9164fd19cbd11be102836ab5886696aff570d638189c54744eac5aa0222e4e115c672ea09b8b9aced2fd552aad0d8fb",
          "sha256": "35ee46a9f54c43b4b3e259d3da73239b6402221158a6e89fbbeaae2e447b266f",
          "sha1": "5638faef67470726244e4fdcaf97e8ad70ae55d5",
          "md5": "96f4afb1000049021c37f4dcdcc26eb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "io.ultreia",
          "module": "bluecove",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.xxxsarutahikoxxx.kotlin",
          "module": "KotlinLibrary",
          "version": {
            "requires": "2.0.7"
          }
        }
      ],
      "files": [
        {
          "name": "HIDDevice-2.0.2.jar",
          "url": "HIDDevice-2.0.2.jar",
          "size": 1056313,
          "sha512": "49219c3de2db6739aa73e6ebfaabd39fc9164fd19cbd11be102836ab5886696aff570d638189c54744eac5aa0222e4e115c672ea09b8b9aced2fd552aad0d8fb",
          "sha256": "35ee46a9f54c43b4b3e259d3da73239b6402221158a6e89fbbeaae2e447b266f",
          "sha1": "5638faef67470726244e4fdcaf97e8ad70ae55d5",
          "md5": "96f4afb1000049021c37f4dcdcc26eb7"
        }
      ]
    }
  ]
}
